### ISSUE TITLE
Code-a-pillar not responding

### ISSUE THREAD

**Issue by nycrchris** [chrisly42/Morph-A-Pillar#1]
I'm really interested in trying to make a custom code-a-pillar segment, but I'm having some difficult getting your example code to work. I acquired some of the digispark clones you appear to be using from your picture, but i've encountered a few issues so far.
-First, the digispark appears to use counter 1 by default for the millis() counter. I changed a config file so that it uses counter 0, and that allowed me to successfully compile your code.
-Next, when plugged into the code-a-pillar, code never actually updated since the code-a-pillar head-unit initialization appeared to interfere with the default micronucleus bootloader code on the digispark. I re-flashed the digispark to use a version of the micronucleus bootloader that relies on a jumper rather than a 5 second delay, and now I can at least successfully execute code on the digispark while it's plugged into the code-a-pillar.

So I'm now executing your unmodified example code while connected to the code-a-pillar, but the code-a-pillar still does not recognize any of the virtual segments. Did you make any additional changes to get it to run?

**Comment by chrisly42** [comment]
Hi there!

First feedback, really appreciated. It's been four years, so I don't really remember much about the thing. Which attiny core did you use for compiling? "attiny" by David A. Mellis seems to be working out of the box (so it's likely that this is what I used, though I did not document it in the README :-/ ) whereas "ATTinyCore" by Spence Konde causes a compile issue with millis() here. Also, I am sure that there were changes to the USB bootloader in the last four years, so I can't really tell whether this affects the startup of the module after flashing.

The code I uploaded here was the last working version that is still flashed on one of my digisparks (I think). I could try to recompile and flash and see if it's still working with the latest attiny core. Please check first, which core you're using.

**Comment by nycrchris** [comment]
Thank you for the quick response! I had initially been trying to use the "Digispark (8mhz - No USB)" core, which caused the millis() timer conflict. I'm currently using the "Micronucleus 1.11" bootloader, which is several years old (the board came with v1.06).

I just installed the attiny core from David Mellis, and ran it with "ATtiny85" processor and "Internal 8 MHz" clock. I just grabbed the .hex file it produced and loaded it with the micronucleus command line tool, which appeared successful, but I still get no response from the code-a-pillar. You were right about this thing being difficult to debug with a digispark!

**Comment by nycrchris** [comment]
As an extra data point - I just tried out a 'blink' test, and it appears that the clock is running roughly twice as fast (I set it to toggle an LED every 5 seconds, and I see it actually toggling every 2.4 seconds, which is probably what's preventing your code from executing correctly).

**Comment by chrisly42** [comment]
Yeah, looks like the frequency is wrong somehow -- not sure, if the bootloader overrides the frequency (fuse) settings (I know some need to use a certain frequency to work for lowspeed USB), but 8 MHz should be correct for the sketch. (I just verified that the bootloader uses 16 or 16.5 MHz.)

I'll try to locate my module and see if I can still get it to work. Debugging is hard, yes. You don't happen to have a scope, do you?

**Comment by chrisly42** [comment]
I found the stump and it still works with the caterpillar (after changing batteries), but I faintly remember that I wasn't using a USB bootloader for flashing (the module has no 5 seconds delay after connecting, the sketch starts straight away), but used a "flying pinheader" with an ISP programmer to flash the stump.

**Comment by nycrchris** [comment]
I looked at it with a scope, and I see that when I plug it into the code-a-pillar the data pin is just getting held low by the AVR (with occasional flashes of bus contention when the code-a-pillar tries to drive it), but I'm 99% sure my issue is still some kind of clocking conflict between the program and the bootloader. The bootloader appears to need it to run at 16 (or 16.5, maybe?) MHz to do the USB emulation. If I set the frequency to 16 MHz in the IDE and load a 'blink' test with delay() statements, things appear to be relatively accurate. With the frequency set to 16 MHz in the IDE, I added a loop to blink several times for 5 seconds (using delay(5000)) the first time loop() executes in your code, however, and it blinks for ~100 mS or so instead, so something is getting pretty messed up. I had been avoiding trying to cobble together an ISP programmer, but maybe I will try that next.

**Comment by nycrchris** [comment]
Success! The issue was being caused by the 'micronucleus' bootloader firmware. I repurposed another arduino board as an Arduino-as-ISP, set the clock to 8 MHz internal, ran 'flash bootloader' to set the fuses, then directly programmed your sketch without the USB bootloader and the code-a-pillar recognized it immediately! I noticed that using "delay()" is still wildly incorrect if I add it to your sketch to try to blink some debug LEDs, so something must be messing with the millis() timer. Now I'm hoping to make a custom segment that will trigger a servo to launch a catapult (probably emulating one of the 'noise-making' segments.

Thank you so much!

**Comment by chrisly42** [comment]
Glad you got it working! A catapult is a great idea! You can probably trigger it when receiving the CMD_LED_BLINK command to the segment. Are you thinking of using it as a middle segment with chaining? That's something I implemented but never tried, because I was too lazy soldering and didn't have a USB socket handy at the time ;)

I'd love to see a picture / video of what you've achieved later...
